* "Unfortunately, no one can be told what The Matrix Theme is. You’ll have to see it for yourself" —Morpheus

** Why?

I was looking for a monochrome green-on-black theme for the darker hours, because for some reason it helps me to focus.

** Themed Packages/Modes

Non-exhaustive list of explicitly themed packages:

- org
- smartparens
- rainbow-delimiters (actually used to make the parens less visible)
- paren-face
- magit
- company
- flymake
- flycheck
- lsp-mode
- eglot
- csv-mode
- css-mode
- web-mode
- slime
- tuareg
- merlin
- merlin-eldoc
- utop
- selectrum
- consult
- helm
- adoc-mode
- highlight-indent-guides
- notmuch
- telega
- beancount
- w3m

** Colors

There are only three base colors used:

- *Matrix Green* Coming in different shades and liminositiy to provide syntax highlighting
- *Blue Pill* for infos, hints, notifications and diff-added
- *Red Pill* for warnings, errors and diff-removed

** Typography

The theme makes use of italic, as well as bold and light weights (if provided by your font). My favorite monospaced font right now is `Recursive'; `Iosevka' should work equally well. For best results, I recommend to configure Emacs' all main faces `default', `fixed-pitch', `fixed-pitch-serif' and `variable-pitch' (optional).

#+caption: Example font config
#+begin_src emacs-lisp
(defun my-fonts ()
  "Set the default fonts."
  (set-face-attribute 'default nil
                      :family "Rec Mono Linear" ; default: "Monospace"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 128)
  (set-face-attribute 'fixed-pitch nil
                      :family "Rec Mono Linear" ; default: "Monospace"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 128)
  (set-face-attribute 'fixed-pitch-serif nil
                      :family "Rec Mono Casual" ; default: "Monospace"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 128)
  (set-face-attribute 'variable-pitch nil
                      :family "Recursive Sans Casual Static" ; default: "Serif"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 128))

;; Modeline
(defun my-modeline ()
  "Custom modeline styling."
  (set-face-attribute 'mode-line nil
                      :family "Rec Mono Linear"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 98)
  (set-face-attribute 'mode-line-inactive nil
                      :family "Rec Mono Linear"
                      :slant  'normal
                      :weight 'normal
                      :width  'normal
                      :height 98))
#+end_src

** Manual Installation

*1.* Create or change to your Emacs themes directory:
#+begin_src sh
  mkdir ~/.emacs.d/themes/
  cd ~/.emacs.d/themes/
#+end_src

*2.* Then clone this repository:
#+begin_src sh
  git clone https://github.com/monkeyjunglejuice/matrix-emacs-theme.git
#+end_src

*3.* Put this in your Emacs init file:
#+caption: Example for Linux/Unix
#+begin_src emacs-lisp
  (let ((basedir "~/.emacs.d/themes/"))
    (dolist (f (directory-files basedir))
      (if (and (not (or (equal f ".") (equal f "..")))
               (file-directory-p (concat basedir f)))
          (add-to-list 'custom-theme-load-path (concat basedir f)))))

  ;; (load-theme 'matrix t) ; uncomment this to load the theme immediately on startup
#+end_src

*4.* (Re)start Emacs. You can now disable your current Emacs theme `M-x disable-theme ... RET' and then `M-x load-theme RET matrix RET'

** Tested with:

- [X] Emacs 27.1 on Ubuntu 21.10
- [X] Emacs 27.1 on Ubuntu 20.04 LTS
- [ ] Emacs 26.1 on Debian 10.9.0
- [ ] Emacs 27 on Windows 10
- [ ] Emacs 26 on Windows 10
- [ ] Emacs 27 on MacOS
- [ ] Emacs 26 on MacOS

** Contribute

If you have issues with the theme or something looks odd, please send a bug report.
You are welcome to add support for further packages/modes.
